[package]
name = "mysqlbinlog-analyzer"
version = "0.1.0"
edition = "2021"
authors = ["Eldad Zack"]
description = "Analyzes the MySQL binlog from the decoded text output"

[dependencies]
anyhow = "1"
clap = { version = "4", features = ["derive", "cargo"] }
lazy_static = "1"
regex = "1"
